name        = "archicheck"
description = "architecture description language and code checker"
version     = "0.5.8"

authors     = ["Lionel Draghi"]
maintainers = ["Lionel Draghi <lionel.draghi@free.fr>"]
maintainers-logins = ["LionelDraghi"]
licenses    = "GPL-3.0-or-later"
website     = "https://github.com/LionelDraghi/ArchiCheck"
tags        = ["code", "architecture", "checker", "static-analysis"]

executables = ["archicheck"]

[[depends-on]]
gnatcov = "^22.0.1"

[configuration]
output_dir   = "src/Alire_config"
generate_C   = false
generate_gpr = false

[[pins]]
opentoken = { path = "../opentoken" } 
