name        = "acc"
description = "architecture description language and code checker"
version     = "0.6.0"

authors     = ["Lionel Draghi"]
maintainers = ["Lionel Draghi <lionel.draghi@free.fr>"]
maintainers-logins = ["LionelDraghi"]
licenses    = "GPL-3.0-or-later"
website     = "https://github.com/LionelDraghi/ArchiCheck"
tags        = ["code", "architecture", "checker", "static-analysis"]

executables = ["acc"]

[configuration]
output_dir   = "src/Alire_config"
generate_C   = false
generate_gpr = false

[[pins]]
opentoken  = { path = "../opentoken" } 
list_image = { path = "../list_image" } 

[[depends-on]]
gnatcov = "^22.0.1"
opentoken = "*"
list_image = "*"

