#-- -----------------------------------------------------------------------------
#--        ArchiCheck, the software architecture compliance verifier
#--           http://lionel.draghi.free.fr/Archicheck/archicheck
#
#-- Copyright (C) 2005-2018 - Lionel Draghi
#-- This program is free software;
#-- you can redistribute it and/or modify it under the terms of the GNU General
#-- Public License Versions 3, refer to the COPYING file.
#-- This file is part of ArchiCheck : http://lionel.draghi.free.fr/Archicheck/archicheck
#-- -----------------------------------------------------------------------------

site_name: ArchiCheck

site_url: http://lionel.draghi.free.fr/Archicheck/index.html
repo_url: https://github.com/LionelDraghi/ArchiCheck
site_description: 'Describe and enforce your software architecture'
site_author: 'Lionel Draghi'

use_directory_urls: true

pages:
- Quick start: index.md

- Documentation:
  - why.md
  - rules.md
  - rules_quick_ref.md
  - cmd_line.md
  - building.md
  - download.md
  
- Current Status:
  - dashboard.md
  - tests/tests_status.md
  ## - fixme.md
  - todo.md
  - Limitations and bugs: limitations.md
  - changelog.md
  - Tests:
    - Common tests:
      - tests/command_line.md
      - tests/source_list.md
      - tests/dependency_list.md
      - tests/component_list.md
      - tests/layer_rule.md
      - tests/child_packages.md
      - tests/rules_files_syntax.md
      - tests/globbing_characters.md
      - tests/use_rule.md
      - tests/rules_on_components.md
      - tests/precedences_rules.md
      - tests/rules_src_coverage.md

    - Ada tests:
      - tests/ada_units.md
      - tests/gtkada.md
      - tests/zipada.md
      - tests/adactl.md
      - tests/archicheck.md

    - Java tests:
      - tests/batik.md
      - tests/petclinic.md
  
  
- About: 
  - about.md
  - contributing.md
  - License: copying.md 

## - Tools:
##   - mdtags.md

# ------------------------------------------------------------------------------
# Les autres tags sont ici:
# http://www.mkdocs.org/user-guide/configuration/

repo_url: https://github.com/LionelDraghi/ArchiCheck
repo_name: GitHub


extra_css:
  - 'lcov/gcov.css'

extra_javascript:
  
# ------------------------------------------------------------------------------
theme: 'material'
# mkdocs
# material
# cinder
# windmill
# amelia
# cerulean
# cosmo
# cyborg
# flatly
# journal
# readable
# simplex
# slate
# spacelab
# united
# yeti
# readthedocs

###  theme_dir: '/usr/local/lib/python2.7/dist-packages/mkdocs_windmill'

# plugins : http://www.mkdocs.org/user-guide/plugins/
# plugins:
#   - search:
#     lang: en
        
# Extensions : https://pythonhosted.org/Markdown/extensions/index.html

markdown_extensions:
    #~ - pymdownx.tasklist