#-- -----------------------------------------------------------------------------
#--        Acc, the software architecture compliance verifier
#--           http://lionel.draghi.free.fr/Archicheck/archicheck
#
#-- Copyright (C) - Lionel Draghi
#-- This program is free software;
#-- you can redistribute it and/or modify it under the terms of the GNU General
#-- Public License Versions 3, refer to the COPYING file.
#-- This file is part of ArchiCheck : http://lionel.draghi.free.fr/Archicheck/archicheck
#-- -----------------------------------------------------------------------------

site_name: ArchiCheck

site_url: http://lionel.draghi.free.fr/Archicheck/index.html
repo_url: https://github.com/LionelDraghi/ArchiCheck
site_description: 'Describe and enforce your software architecture'
site_author: 'Lionel Draghi'

use_directory_urls: true

nav:
- Quick start: index.md

- Documentation:
  - why.md
  - acc_concepts.md
  - rules.md
  - languages_concepts.md
  # Fixme: - rules_quick_ref.md
  - cmd_line.md
  - design_overview.md
  - tests_overview.md
  - building.md
  - download.md
  
- Current Status:
  - dashboard.md
  - tests/tests_status.md
  - tests/test_results.md
  - fixme.md
  - todo.md
  - Limitations and bugs: limitations.md
  - changelog.md
  - Tests:
    - Common tests:
      - tests/01_command_line.md
      - tests/02_source_list.md
      - tests/03_dependency_list.md
      - tests/04_component_list.md
      - tests/05_layer_rule.md
      - tests/06_child_packages.md
      - tests/07_rules_files_syntax.md
      - tests/08_globbing_characters.md
      - tests/use_rule.md
      - tests/rules_on_components.md
      - tests/precedences_rules.md
      - tests/rules_src_coverage.md

    - Ada tests:
      - tests/ada_units.md
      - tests/gtkada.md
      - tests/zipada.md
      - tests/adactl.md
      # tests/acc.md

    - Java tests:
      - tests/batik.md
      - tests/petclinic.md
  
    - C tests:
      - tests/C_sanity_check.md

- About: 
  - about.md
  - contributing.md
  - License: copying.md 

## - Tools:
##   - mdtags.md

# ------------------------------------------------------------------------------
# Les autres tags sont ici:
# http://www.mkdocs.org/user-guide/configuration/

repo_url: https://github.com/LionelDraghi/ArchiCheck
repo_name: GitHub


extra_css:
  - 'lcov/gcov.css'

# extra_javascript:
  
# ------------------------------------------------------------------------------
theme: material # nature # material # bootstrap

# plugins : http://www.mkdocs.org/user-guide/plugins/
# plugins:
#   - search:
#     lang: en
        
# Extensions : https://pythonhosted.org/Markdown/extensions/index.html

markdown_extensions:
    #~ - pymdownx.tasklist