# ------------------------------------------------------------------------------
site_name: ArchiCheck

site_url: http://lionel.draghi.free.fr/Archicheck/index.html
repo_url: https://github.com/LionelDraghi/ArchiCheck
site_description: 'Describe and enforce your software architecture'
site_author: 'Lionel Draghi'

use_directory_urls: true

pages:
- Quick start: index.md
- About: about.md

- Documentation:
  - rules.md
  - cmd_line.md
  - building.md
  - copying.md
  
- Current Status:
  - dashboard.md
  - tests/tests_status.md
  ## - fixme.md
  - download.md
  - todo.md
  
- Tests:
  - tests/command_line.md
  - tests/source_list.md
  - tests/dependency_list.md
  - tests/component_list.md
  - tests/layer_rule.md
  - tests/child_packages.md
  - tests/rules_files_syntax.md
  - tests/globbing_characters.md
  - tests/use_rule.md
  - tests/ada_units.md
  - tests/rules_on_components.md
  - tests/precedences_rules.md

- Real software tests:
  - tests/gtkada.md
  - tests/batik.md
  - tests/zipada.md
  - tests/adactl.md

## - Tools:
##   - mdtags.md


# ------------------------------------------------------------------------------
# Les autres tags sont ici:
# http://www.mkdocs.org/user-guide/configuration/

repo_url: https://github.com/LionelDraghi/ArchiCheck
repo_name: GitHub


extra_css:
  - 'lcov/gcov.css'

extra_javascript:
  
# ------------------------------------------------------------------------------
theme: 'material'
# mkdocs
# material
# cinder
# windmill
# amelia
# cerulean
# cosmo
# cyborg
# flatly
# journal
# readable
# simplex
# slate
# spacelab
# united
# yeti
# readthedocs

###  theme_dir: '/usr/local/lib/python2.7/dist-packages/mkdocs_windmill'

# plugins : http://www.mkdocs.org/user-guide/plugins/
# plugins:
#   - search:
#     lang: en
        
# Extensions : https://pythonhosted.org/Markdown/extensions/index.html

markdown_extensions:
    #~ - pymdownx.tasklist