Applications      contains org.apache.batik.apps.svgbrowser and org.apache.batik.apps.rasterizer
Core_Modules      contains org.apache.batik.UI_Component, org.apache.batik.transcoder, org.apache.batik.SVGGen, org.apache.batik.Bridge and org.apache.batik.dom.svg
Low_Level_Modules contains org.apache.batik.gvt.renderer, org.apache.batik.GVT and org.apache.batik.Parser

Applications is a layer over Core_Modules
Core_Modules is a layer over Low_Level_Modules
