name        = "create_pkg"
description = "test data generator for the ArchiCheck test suites"
version     = "1.1.0"

authors     = ["Lionel Draghi"]
maintainers = ["Lionel Draghi <lionel.draghi@free.fr>"]
maintainers-logins = ["LionelDraghi"]
licenses    = "GPL-3.0-or-later"
website     = ""
tags        = ["test"]

project-files = ["create_pkg.gpr"]
executables = ["create_pkg"]

[configuration]
output_dir   = "src/Alire_config"
generate_C   = false
